type: object
properties:
    amount:
        type: number
        format: double
    description:
        type: string
    createdAt:
        type: string
        format: date-time
required:
    - amount
    - description
    - createdAt