type: object
properties:
    id:
        type: integer
    amount:
        type: number
        format: double
    percent:
        type: number
        format: double
    average:
        type: number
        format: double
    categoryId:
        type: integer
    transactionsCount:
        type: integer
    categoryDescription:
        type: string
required:
    - id
    - amount
    - percent
    - average
    - categoryId
    - transactionsCount
    - categoryDescription
