post:
    tags: [ "user-management" ]
    operationId: "registration"
    security: []
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    $ref: '../../../components/user/management/UserRegistration.yaml'
    responses:
        '200':
            description: OK
        '403':
            description: Bad Request
            content:
                application/json:
                    schema:
                        $ref: '../../../components/error/Error.yaml'