/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics;


import com.oleg.fund.customer.costs.analytics.tables.Bank;
import com.oleg.fund.customer.costs.analytics.tables.CostsCategory;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCosts;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsEvents;
import com.oleg.fund.customer.costs.analytics.tables.MonobankUserAccounts;
import com.oleg.fund.customer.costs.analytics.tables.UserBank;
import com.oleg.fund.customer.costs.analytics.tables.UserDetails;
import com.oleg.fund.customer.costs.analytics.tables.UserSpending;
import com.oleg.fund.customer.costs.analytics.tables.UserTokens;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.bank</code>.
     */
    public static final Bank BANK = Bank.BANK;

    /**
     * The table <code>public.costs_category</code>.
     */
    public static final CostsCategory COSTS_CATEGORY = CostsCategory.COSTS_CATEGORY;

    /**
     * The table <code>public.customer_costs</code>.
     */
    public static final CustomerCosts CUSTOMER_COSTS = CustomerCosts.CUSTOMER_COSTS;

    /**
     * The table <code>public.customer_costs_events</code>.
     */
    public static final CustomerCostsEvents CUSTOMER_COSTS_EVENTS = CustomerCostsEvents.CUSTOMER_COSTS_EVENTS;

    /**
     * The table <code>public.monobank_user_accounts</code>.
     */
    public static final MonobankUserAccounts MONOBANK_USER_ACCOUNTS = MonobankUserAccounts.MONOBANK_USER_ACCOUNTS;

    /**
     * The table <code>public.user_bank</code>.
     */
    public static final UserBank USER_BANK = UserBank.USER_BANK;

    /**
     * The table <code>public.user_details</code>.
     */
    public static final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;

    /**
     * The table <code>public.user_spending</code>.
     */
    public static final UserSpending USER_SPENDING = UserSpending.USER_SPENDING;

    /**
     * The table <code>public.user_tokens</code>.
     */
    public static final UserTokens USER_TOKENS = UserTokens.USER_TOKENS;
}
