openapi: 3.0.0

info:
    version: 1.0.0
    title: Customer Costs Analytics Open API
paths:
    /banks/supported:
        $ref: 'paths/bank/banks.yaml'
    /user/banks:
        $ref: 'paths/bank/userBanks.yaml'
    /user/banks/{bankId}/costs:
        $ref: 'paths/bank/userBankCosts.yaml'
    /user/banks/{bankId}/costs/count:
        $ref: 'paths/bank/userBankCostsCount.yaml'
    /user/management/login:
        $ref: 'paths/user/management/login.yaml'
    /user/management/registration:
        $ref: 'paths/user/management/registration.yaml'