/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CostsCategoryEmbedding extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.costs_category_embedding</code>
     */
    public static final CostsCategoryEmbedding COSTS_CATEGORY_EMBEDDING = new CostsCategoryEmbedding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.costs_category_embedding.category_id</code>.
     */
    public final TableField<Record, Integer> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.costs_category_embedding.embedding</code>.
     */
    public final TableField<Record, Double[]> EMBEDDING = createField(DSL.name("embedding"), SQLDataType.FLOAT.nullable(false).array(), this, "");

    private CostsCategoryEmbedding(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CostsCategoryEmbedding(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.costs_category_embedding</code> table
     * reference
     */
    public CostsCategoryEmbedding(String alias) {
        this(DSL.name(alias), COSTS_CATEGORY_EMBEDDING);
    }

    /**
     * Create an aliased <code>public.costs_category_embedding</code> table
     * reference
     */
    public CostsCategoryEmbedding(Name alias) {
        this(alias, COSTS_CATEGORY_EMBEDDING);
    }

    /**
     * Create a <code>public.costs_category_embedding</code> table reference
     */
    public CostsCategoryEmbedding() {
        this(DSL.name("costs_category_embedding"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(CostsCategoryEmbedding.COSTS_CATEGORY_EMBEDDING, DSL.name("costs_category_embedding_pkey"), new TableField[] { CostsCategoryEmbedding.COSTS_CATEGORY_EMBEDDING.CATEGORY_ID }, true);
    }

    @Override
    public CostsCategoryEmbedding as(String alias) {
        return new CostsCategoryEmbedding(DSL.name(alias), this);
    }

    @Override
    public CostsCategoryEmbedding as(Name alias) {
        return new CostsCategoryEmbedding(alias, this);
    }

    @Override
    public CostsCategoryEmbedding as(Table<?> alias) {
        return new CostsCategoryEmbedding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CostsCategoryEmbedding rename(String name) {
        return new CostsCategoryEmbedding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CostsCategoryEmbedding rename(Name name) {
        return new CostsCategoryEmbedding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CostsCategoryEmbedding rename(Table<?> name) {
        return new CostsCategoryEmbedding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding where(Condition condition) {
        return new CostsCategoryEmbedding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CostsCategoryEmbedding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CostsCategoryEmbedding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CostsCategoryEmbedding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CostsCategoryEmbedding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CostsCategoryEmbedding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
