/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCostsEvents extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_costs_events</code>
     */
    public static final CustomerCostsEvents CUSTOMER_COSTS_EVENTS = new CustomerCostsEvents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.customer_costs_events.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.customer_costs_events.processed</code>.
     */
    public final TableField<Record, Boolean> PROCESSED = createField(DSL.name("processed"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.customer_costs_events.customer_costs_id</code>.
     */
    public final TableField<Record, Integer> CUSTOMER_COSTS_ID = createField(DSL.name("customer_costs_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private CustomerCostsEvents(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerCostsEvents(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_costs_events</code> table
     * reference
     */
    public CustomerCostsEvents(String alias) {
        this(DSL.name(alias), CUSTOMER_COSTS_EVENTS);
    }

    /**
     * Create an aliased <code>public.customer_costs_events</code> table
     * reference
     */
    public CustomerCostsEvents(Name alias) {
        this(alias, CUSTOMER_COSTS_EVENTS);
    }

    /**
     * Create a <code>public.customer_costs_events</code> table reference
     */
    public CustomerCostsEvents() {
        this(DSL.name("customer_costs_events"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(CustomerCostsEvents.CUSTOMER_COSTS_EVENTS, DSL.name("customer_costs_events_pkey"), new TableField[] { CustomerCostsEvents.CUSTOMER_COSTS_EVENTS.ID }, true);
    }

    @Override
    public CustomerCostsEvents as(String alias) {
        return new CustomerCostsEvents(DSL.name(alias), this);
    }

    @Override
    public CustomerCostsEvents as(Name alias) {
        return new CustomerCostsEvents(alias, this);
    }

    @Override
    public CustomerCostsEvents as(Table<?> alias) {
        return new CustomerCostsEvents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsEvents rename(String name) {
        return new CustomerCostsEvents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsEvents rename(Name name) {
        return new CustomerCostsEvents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsEvents rename(Table<?> name) {
        return new CustomerCostsEvents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents where(Condition condition) {
        return new CustomerCostsEvents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsEvents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsEvents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsEvents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsEvents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsEvents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
