/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserTokens extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_tokens</code>
     */
    public static final UserTokens USER_TOKENS = new UserTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_tokens.user_id</code>.
     */
    public final TableField<Record, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_tokens.bank_id</code>.
     */
    public final TableField<Record, Integer> BANK_ID = createField(DSL.name("bank_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_tokens.token</code>.
     */
    public final TableField<Record, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR.nullable(false), this, "");

    private UserTokens(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserTokens(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_tokens</code> table reference
     */
    public UserTokens(String alias) {
        this(DSL.name(alias), USER_TOKENS);
    }

    /**
     * Create an aliased <code>public.user_tokens</code> table reference
     */
    public UserTokens(Name alias) {
        this(alias, USER_TOKENS);
    }

    /**
     * Create a <code>public.user_tokens</code> table reference
     */
    public UserTokens() {
        this(DSL.name("user_tokens"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(UserTokens.USER_TOKENS, DSL.name("user_tokens_pkey"), new TableField[] { UserTokens.USER_TOKENS.USER_ID, UserTokens.USER_TOKENS.BANK_ID }, true);
    }

    @Override
    public UserTokens as(String alias) {
        return new UserTokens(DSL.name(alias), this);
    }

    @Override
    public UserTokens as(Name alias) {
        return new UserTokens(alias, this);
    }

    @Override
    public UserTokens as(Table<?> alias) {
        return new UserTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTokens rename(String name) {
        return new UserTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTokens rename(Name name) {
        return new UserTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTokens rename(Table<?> name) {
        return new UserTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens where(Condition condition) {
        return new UserTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
