/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserSpending extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_spending</code>
     */
    public static final UserSpending USER_SPENDING = new UserSpending();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_spending.max_amount</code>.
     */
    public final TableField<Record, BigDecimal> MAX_AMOUNT = createField(DSL.name("max_amount"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.user_spending.period</code>.
     */
    public final TableField<Record, Integer> PERIOD = createField(DSL.name("period"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_spending.bank_id</code>.
     */
    public final TableField<Record, Integer> BANK_ID = createField(DSL.name("bank_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_spending.current_amount</code>.
     */
    public final TableField<Record, BigDecimal> CURRENT_AMOUNT = createField(DSL.name("current_amount"), SQLDataType.NUMERIC.nullable(false).defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.user_spending.user_id</code>.
     */
    public final TableField<Record, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserSpending(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserSpending(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_spending</code> table reference
     */
    public UserSpending(String alias) {
        this(DSL.name(alias), USER_SPENDING);
    }

    /**
     * Create an aliased <code>public.user_spending</code> table reference
     */
    public UserSpending(Name alias) {
        this(alias, USER_SPENDING);
    }

    /**
     * Create a <code>public.user_spending</code> table reference
     */
    public UserSpending() {
        this(DSL.name("user_spending"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(UserSpending.USER_SPENDING, DSL.name("user_spending_pkey"), new TableField[] { UserSpending.USER_SPENDING.USER_ID, UserSpending.USER_SPENDING.BANK_ID, UserSpending.USER_SPENDING.PERIOD }, true);
    }

    @Override
    public UserSpending as(String alias) {
        return new UserSpending(DSL.name(alias), this);
    }

    @Override
    public UserSpending as(Name alias) {
        return new UserSpending(alias, this);
    }

    @Override
    public UserSpending as(Table<?> alias) {
        return new UserSpending(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSpending rename(String name) {
        return new UserSpending(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSpending rename(Name name) {
        return new UserSpending(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSpending rename(Table<?> name) {
        return new UserSpending(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending where(Condition condition) {
        return new UserSpending(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSpending where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSpending where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSpending where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSpending where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSpending whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
