get:
    tags: [ "period-costs-analytics" ]
    operationId: "getAnalyticsPeriods"
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        $ref: '../../components/period/AnalyticPeriods.yaml'
        '403':
            description: Not Authorized
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'
        '404':
            description: Not Found
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'