get:
    tags: [ "period-costs-analytics" ]
    operationId: "getPeriodCostsAnalytics"
    parameters:
        - name: id
          in: path
          required: true
          schema:
              type: integer
        -   name: limit
            in: query
            schema:
                type: integer
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        $ref: '../../components/period/PeriodCostsAnalyticsResponse.yaml'
        '403':
            description: Not Authorized
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'
        '404':
            description: Not Found
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'