get:
    tags: [ "user-banks" ]
    operationId: "getUserBanks"
    security: []
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        $ref: '../../components/bank/BanksList.yaml'
        '404':
            description: Not Found
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'
post:
    tags: [ "user-banks" ]
    operationId: "addUserBank"
    security: []
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '../../components/bank/AddUserBank.yaml'
    responses:
        '200':
            description: OK
        '403':
            description: Not Found
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'
delete:
    parameters:
        -   name: bankId
            in: query
            required: true
            schema:
                type: integer
    security: []
    tags: [ "user-banks" ]
    operationId: "deleteBank"
    responses:
        '200':
            description: OK
        '403':
            description: Not Found
            content:
                application/json:
                    schema:
                        $ref: '../../components/error/Error.yaml'