name: CI

on:
    pull_request:
        branches: ["*"]
    push:
        branches: ["main"]

jobs:
    docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: "21"

            - name: Build & Push with Jib
              env:
                  IMAGE_VERSION: ${{ github.sha }}
                  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
              run: ./gradlew jib
    library_publish:
        name: Build and Push OpenApi Library
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: "21"
            -   name: Publish OpenAPI to GitHub Packages
                continue-on-error: true
                env:
                    GPR_TOKEN: ${{ secrets.PACKAGE_PUBLISH_TOKEN }}
                run: ./gradlew publish