/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCosts extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_costs</code>
     */
    public static final CustomerCosts CUSTOMER_COSTS = new CustomerCosts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.customer_costs.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.customer_costs.bank_id</code>.
     */
    public final TableField<Record, Integer> BANK_ID = createField(DSL.name("bank_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.user_id</code>.
     */
    public final TableField<Record, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.category_id</code>.
     */
    public final TableField<Record, Integer> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.amount</code>.
     */
    public final TableField<Record, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.created_at</code>.
     */
    public final TableField<Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.customer_costs.commission_rate</code>.
     */
    public final TableField<Record, BigDecimal> COMMISSION_RATE = createField(DSL.name("commission_rate"), SQLDataType.NUMERIC.nullable(false).defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.NUMERIC)), this, "");

    private CustomerCosts(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerCosts(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_costs</code> table reference
     */
    public CustomerCosts(String alias) {
        this(DSL.name(alias), CUSTOMER_COSTS);
    }

    /**
     * Create an aliased <code>public.customer_costs</code> table reference
     */
    public CustomerCosts(Name alias) {
        this(alias, CUSTOMER_COSTS);
    }

    /**
     * Create a <code>public.customer_costs</code> table reference
     */
    public CustomerCosts() {
        this(DSL.name("customer_costs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(CustomerCosts.CUSTOMER_COSTS, DSL.name("customer_costs_pkey"), new TableField[] { CustomerCosts.CUSTOMER_COSTS.ID }, true);
    }

    @Override
    public CustomerCosts as(String alias) {
        return new CustomerCosts(DSL.name(alias), this);
    }

    @Override
    public CustomerCosts as(Name alias) {
        return new CustomerCosts(alias, this);
    }

    @Override
    public CustomerCosts as(Table<?> alias) {
        return new CustomerCosts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCosts rename(String name) {
        return new CustomerCosts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCosts rename(Name name) {
        return new CustomerCosts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCosts rename(Table<?> name) {
        return new CustomerCosts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts where(Condition condition) {
        return new CustomerCosts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCosts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCosts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCosts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCosts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCosts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
