/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCostsByPeriod extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_costs_by_period</code>
     */
    public static final CustomerCostsByPeriod CUSTOMER_COSTS_BY_PERIOD = new CustomerCostsByPeriod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column
     * <code>public.customer_costs_by_period.customer_costs_id</code>.
     */
    public final TableField<Record, Integer> CUSTOMER_COSTS_ID = createField(DSL.name("customer_costs_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.customer_costs_by_period.period_costs_analytics_id</code>.
     */
    public final TableField<Record, Integer> PERIOD_COSTS_ANALYTICS_ID = createField(DSL.name("period_costs_analytics_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private CustomerCostsByPeriod(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerCostsByPeriod(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_costs_by_period</code> table
     * reference
     */
    public CustomerCostsByPeriod(String alias) {
        this(DSL.name(alias), CUSTOMER_COSTS_BY_PERIOD);
    }

    /**
     * Create an aliased <code>public.customer_costs_by_period</code> table
     * reference
     */
    public CustomerCostsByPeriod(Name alias) {
        this(alias, CUSTOMER_COSTS_BY_PERIOD);
    }

    /**
     * Create a <code>public.customer_costs_by_period</code> table reference
     */
    public CustomerCostsByPeriod() {
        this(DSL.name("customer_costs_by_period"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public CustomerCostsByPeriod as(String alias) {
        return new CustomerCostsByPeriod(DSL.name(alias), this);
    }

    @Override
    public CustomerCostsByPeriod as(Name alias) {
        return new CustomerCostsByPeriod(alias, this);
    }

    @Override
    public CustomerCostsByPeriod as(Table<?> alias) {
        return new CustomerCostsByPeriod(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsByPeriod rename(String name) {
        return new CustomerCostsByPeriod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsByPeriod rename(Name name) {
        return new CustomerCostsByPeriod(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsByPeriod rename(Table<?> name) {
        return new CustomerCostsByPeriod(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod where(Condition condition) {
        return new CustomerCostsByPeriod(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsByPeriod where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsByPeriod where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsByPeriod where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsByPeriod where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsByPeriod whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
