/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonobankUserAccounts extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.monobank_user_accounts</code>
     */
    public static final MonobankUserAccounts MONOBANK_USER_ACCOUNTS = new MonobankUserAccounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.monobank_user_accounts.account_id</code>.
     */
    public final TableField<Record, String> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.monobank_user_accounts.user_id</code>.
     */
    public final TableField<Record, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private MonobankUserAccounts(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MonobankUserAccounts(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.monobank_user_accounts</code> table
     * reference
     */
    public MonobankUserAccounts(String alias) {
        this(DSL.name(alias), MONOBANK_USER_ACCOUNTS);
    }

    /**
     * Create an aliased <code>public.monobank_user_accounts</code> table
     * reference
     */
    public MonobankUserAccounts(Name alias) {
        this(alias, MONOBANK_USER_ACCOUNTS);
    }

    /**
     * Create a <code>public.monobank_user_accounts</code> table reference
     */
    public MonobankUserAccounts() {
        this(DSL.name("monobank_user_accounts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public MonobankUserAccounts as(String alias) {
        return new MonobankUserAccounts(DSL.name(alias), this);
    }

    @Override
    public MonobankUserAccounts as(Name alias) {
        return new MonobankUserAccounts(alias, this);
    }

    @Override
    public MonobankUserAccounts as(Table<?> alias) {
        return new MonobankUserAccounts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MonobankUserAccounts rename(String name) {
        return new MonobankUserAccounts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonobankUserAccounts rename(Name name) {
        return new MonobankUserAccounts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonobankUserAccounts rename(Table<?> name) {
        return new MonobankUserAccounts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts where(Condition condition) {
        return new MonobankUserAccounts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonobankUserAccounts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonobankUserAccounts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonobankUserAccounts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonobankUserAccounts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonobankUserAccounts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
